import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getAllPosts } from './api/api'

const Home = ({ allPosts }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Testing Markdowns</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>Im Kris</h2>
      {allPosts.map((post) => (
        <div key={post.slug}>
          <p>
            <Link as={`/posts/${post.slug}`} href="/posts/[slug]">
              <a className="hover:underline">{post.title}</a>
            </Link>
          </p>
          <p>{post.date}</p>
          <p>{post.author.name}</p>
          <div>---</div>
        </div>
      ))}
    </div>
  )
}

export default Home;

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'coverImage',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}
